# Generated by Django 2.1.7 on 2019-04-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=4, default=None, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=4, default=None, max_digits=10)),
            ],
        ),
    ]
