# Generated by Django 2.1.7 on 2019-04-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
    ]
